# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test-lnx
'on': [pull_request, push]
jobs:
  test-lnx:
    name: Test ${{ matrix.img }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        img:
          - alpine
          - archlinux
          - debian
          - fedora
          - ubi8
          - ubi9
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt update
          sudo apt install --yes podman
      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./container/${{ matrix.img }}/Containerfile
          image: ${{ matrix.img }}
          tags: latest
      - run: |
          podman run --rm ${{ matrix.img }}:latest lint test
